name: Prova1
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49229
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#31aeaa'
    - '#a1d6aa'
    - '#fff8f0'
    - '#0077a7'
    - '#547b84'
  brandStrength: 0.32571867876686156
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
